### ISSUE TITLE
Flashing on the wrong USB port

### ISSUE THREAD

**Issue by Mohaabenz** [institut-galilee/Lab-One#8]
Generating esp32.common.ld
esptool.py v2.6-beta1
Flashing binaries to serial port /dev/ttyUSB0 (app at offset 0x10000)...
esptool.py v2.6-beta1
Serial port D:/momo_/Documents/IOT/msys32/dev/ttyUSB0
Traceback (most recent call last):
  File "D:/momo_/Documents/IOT/msys32/home/momo_/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2865, in <module>
    _main()
  File "D:/momo_/Documents/IOT/msys32/home/momo_/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2858, in _main
    main()
  File "D:/momo_/Documents/IOT/msys32/home/momo_/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2565, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "D:/momo_/Documents/IOT/msys32/home/momo_/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 213, in __init__
    self._port = serial.serial_for_url(port)
  File "D:/momo_/Documents/IOT/msys32/mingw32/lib/python2.7/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "D:/momo_/Documents/IOT/msys32/mingw32/lib/python2.7/site-packages/serial/serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'D:/momo_/Documents/IOT/msys32/dev/ttyUSB0': WindowsError(2, 'Le fichier sp\xe9cifi\xe9 est introuvable.')
make: *** [/home/momo_/esp/esp-idf/components/esptool_py/Makefile.projbuild:63: flash] Error 1
-bash: Generating : commande introuvable

**Comment by HamidiMassinissa** [comment]
As discussed together, you are trying to flash the `esp32` through port `/dev/ttyUSB0` which is not defined.
The solution is then to change this port via `make menuconfig` and name it after the one that is displayed in the `Windows device manager`.
